INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 7;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 3;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 9;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 25;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 4;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 2;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 5;
INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS
FROM cadfun WHERE CODFUN = 15;
DELETE FROM cadfun WHERE CODFUN = 7;
DELETE FROM cadfun WHERE CODFUN = 3;
DELETE FROM cadfun WHERE CODFUN = 9;
DELETE FROM cadfun WHERE CODFUN = 25;
DELETE FROM cadfun WHERE CODFUN = 4;
DELETE FROM cadfun WHERE CODFUN = 2;
DELETE FROM cadfun WHERE CODFUN = 5;
DELETE FROM cadfun WHERE CODFUN = 15;
SELECT CODFUN, NOME FROM cadfun;
SELECT CODFUN, NOME FROM morto;
SELECT CODFUN, NOME FROM cadfun UNION SELECT CODFUN, NOME FROM morto;
INSERT INTO morto VALUES (
21,
'EPAMINONDAS DA SILVA',
'4',
'PROGRAMADOR',
1155.00,
'2006-10-10',
2
);
SELECT CODFUN, NOME FROM cadfun;
SELECT CODFUN, NOME FROM morto;
SELECT CODFUN, NOME FROM cadfun UNION SELECT CODFUN, NOME FROM morto;
SELECT CODFUN, NOME FROM cadfun UNION ALL SELECT CODFUN, NOME FROM morto;