SELECT DEPTO, COUNT(*) FROM cadfun GROUP BY DEPTO;
SELECT FUNCAO, COUNT(*) FROM cadfun GROUP BY FUNCAO;
SELECT DEPTO, SUM(SALARIO) FROM cadfun GROUP BY DEPTO;
SELECT DEPTO, SUM(SALARIO) FROM cadfun WHERE DEPTO IN ('2', '4') GROUP BY DEPTO;
SELECT DEPTO, COUNT(*) FROM cadfun GROUP BY DEPTO ORDER BY DEPTO;
SELECT DEPTO, SUM(SALARIO) FROM cadfun GROUP BY DEPTO
HAVING SUM(SALARIO) > 8000;