-- MySQL Script generated by MySQL Workbench
-- 09/24/17 14:05:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comforne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comforne` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comforne` (
  `n_numeforne` INT(11) NOT NULL,
  `c_codiforne` VARCHAR(10) NULL,
  `c_nomeforne` VARCHAR(50) NULL,
  `c_razaforne` VARCHAR(50) NULL,
  `c_foneforne` VARCHAR(15) NULL,
  PRIMARY KEY (`n_numeforne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comclien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comclien` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comclien` (
  `n_numeclien` INT(11) NOT NULL,
  `c_codiclien` VARCHAR(10) NULL,
  `c_nomeclien` VARCHAR(100) NULL,
  `c_razaclien` VARCHAR(100) NULL,
  `d_dataclien` DATE NULL,
  `c_cnpjclien` VARCHAR(30) NULL,
  `c_foneclien` VARCHAR(15) NULL,
  `c_cidaclien` VARCHAR(50) NULL,
  `c_estaclien` VARCHAR(100) NULL,
  `comforne_n_numeforne` INT(11) NOT NULL,
  PRIMARY KEY (`n_numeclien`),
  INDEX `fk_comclien_comforne1_idx` (`comforne_n_numeforne` ASC),
  CONSTRAINT `fk_comclien_comforne1`
    FOREIGN KEY (`comforne_n_numeforne`)
    REFERENCES `mydb`.`comforne` (`n_numeforne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comvende`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comvende` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comvende` (
  `n_numevende` INT(11) NOT NULL,
  `c_codivende` VARCHAR(10) NULL,
  `c_nomevende` VARCHAR(50) NULL,
  `c_razavende` VARCHAR(50) NULL,
  `c_fonevende` VARCHAR(50) NULL,
  `n_porcvende` FLOAT(10,2) NULL,
  PRIMARY KEY (`n_numevende`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comvenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comvenda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comvenda` (
  `n_numevenda` INT(11) NOT NULL,
  `c_codivenda` VARCHAR(10) NULL,
  `n_numeclien` INT(11) NULL,
  `n_numeforne` INT(11) NULL,
  `n_valovenda` FLOAT(10,2) NULL,
  `n_descvenda` FLOAT(10,2) NULL,
  `n_totavenda` FLOAT(10,2) NULL,
  `d_datavenda` DATE NULL,
  `n_vcomvenda` FLOAT(10,2) NULL,
  `n_numevende` INT(11) NULL,
  `comvende_n_numevende` INT(11) NOT NULL,
  `comforne_n_numeforne` INT(11) NOT NULL,
  PRIMARY KEY (`n_numevenda`),
  INDEX `fk_comvenda_comvende_idx` (`comvende_n_numevende` ASC),
  INDEX `fk_comvenda_comforne1_idx` (`comforne_n_numeforne` ASC),
  CONSTRAINT `fk_comvenda_comvende`
    FOREIGN KEY (`comvende_n_numevende`)
    REFERENCES `mydb`.`comvende` (`n_numevende`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comvenda_comforne1`
    FOREIGN KEY (`comforne_n_numeforne`)
    REFERENCES `mydb`.`comforne` (`n_numeforne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comprodu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comprodu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comprodu` (
  `n_numeprodu` INT(11) NOT NULL,
  `c_codiprodu` VARCHAR(20) NULL,
  `c_descprodu` VARCHAR(100) NULL,
  `n_valoprodu` FLOAT(10,2) NULL,
  `c_situprodu` VARCHAR(1) NULL,
  `n_numeforne` VARCHAR(11) NULL,
  `comvenda_n_numevenda` INT(11) NOT NULL,
  PRIMARY KEY (`n_numeprodu`),
  INDEX `fk_comprodu_comvenda1_idx` (`comvenda_n_numevenda` ASC),
  CONSTRAINT `fk_comprodu_comvenda1`
    FOREIGN KEY (`comvenda_n_numevenda`)
    REFERENCES `mydb`.`comvenda` (`n_numevenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comivenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comivenda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comivenda` (
  `n_numeivenda` INT(11) NOT NULL,
  `n_numevenda` INT(11) NULL,
  `n_numeprodu` INT(11) NULL,
  `n_valoivenda` FLOAT(10,2) NULL,
  `n_qtdeivenda` INT(11) NULL,
  `n_descivenda` FLOAT(10,2) NULL,
  `comclien_n_numeclien` INT(11) NOT NULL,
  PRIMARY KEY (`n_numeivenda`),
  INDEX `fk_comivenda_comclien1_idx` (`comclien_n_numeclien` ASC),
  CONSTRAINT `fk_comivenda_comclien1`
    FOREIGN KEY (`comclien_n_numeclien`)
    REFERENCES `mydb`.`comclien` (`n_numeclien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
