-- MySQL Script generated by MySQL Workbench
-- 10/09/17 01:03:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ex2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex2` DEFAULT CHARACTER SET latin1 ;
USE `ex2` ;

-- -----------------------------------------------------
-- Table `ex2`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex2`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ex2`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` INT(13) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex2`.`dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex2`.`dependente` ;

CREATE TABLE IF NOT EXISTS `ex2`.`dependente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `Cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dependente_Cliente_idx` (`Cliente_id` ASC),
  CONSTRAINT `fk_dependente_Cliente`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `ex2`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
