-- MySQL Script generated by MySQL Workbench
-- 10/09/17 01:47:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ex3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex3` DEFAULT CHARACTER SET latin1 ;
USE `ex3` ;

-- -----------------------------------------------------
-- Table `ex3`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`departamento` ;

CREATE TABLE IF NOT EXISTS `ex3`.`departamento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex3`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `ex3`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_departamento_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_funcionario_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `ex3`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
