-- MySQL Script generated by MySQL Workbench
-- 10/15/17 14:51:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ex4` ;

-- -----------------------------------------------------
-- Schema ex4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex4` DEFAULT CHARACTER SET latin1 ;
USE `ex4` ;

-- -----------------------------------------------------
-- Table `ex4`.`filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex4`.`filme` ;

CREATE TABLE IF NOT EXISTS `ex4`.`filme` (
  `id` INT(10) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `ano` INT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex4`.`ator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex4`.`ator` ;

CREATE TABLE IF NOT EXISTS `ex4`.`ator` (
  `id` INT(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex4`.`atuacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex4`.`atuacao` ;

CREATE TABLE IF NOT EXISTS `ex4`.`atuacao` (
  `filme_id` INT(10) NOT NULL,
  `ator_id` INT(10) NOT NULL,
  INDEX `fk_atuacao_filme_idx` (`filme_id` ASC),
  INDEX `fk_atuacao_ator1_idx` (`ator_id` ASC),
  CONSTRAINT `fk_atuacao_filme`
    FOREIGN KEY (`filme_id`)
    REFERENCES `ex4`.`filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atuacao_ator1`
    FOREIGN KEY (`ator_id`)
    REFERENCES `ex4`.`ator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
