-- MySQL Script generated by MySQL Workbench
-- 10/15/17 15:47:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex7
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ex7` ;

-- -----------------------------------------------------
-- Schema ex7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex7` DEFAULT CHARACTER SET latin1 ;
USE `ex7` ;

-- -----------------------------------------------------
-- Table `ex7`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex7`.`produto` ;

CREATE TABLE IF NOT EXISTS `ex7`.`produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex7`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex7`.`venda` ;

CREATE TABLE IF NOT EXISTS `ex7`.`venda` (
  `id` INT(10) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex7`.`item venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex7`.`item venda` ;

CREATE TABLE IF NOT EXISTS `ex7`.`item venda` (
  `venda_id` INT(10) NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `precovendido` DECIMAL(10,2) NOT NULL,
  INDEX `fk_item venda_produto_idx` (`produto_id` ASC),
  INDEX `fk_item venda_venda1_idx` (`venda_id` ASC),
  CONSTRAINT `fk_item venda_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ex7`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `ex7`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
