-- MySQL Script generated by MySQL Workbench
-- 10/15/17 15:13:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ex5` ;

-- -----------------------------------------------------
-- Schema ex5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex5` DEFAULT CHARACTER SET latin1 ;
USE `ex5` ;

-- -----------------------------------------------------
-- Table `ex5`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex5`.`produto` ;

CREATE TABLE IF NOT EXISTS `ex5`.`produto` (
  `id` INT(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex5`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex5`.`categoria` ;

CREATE TABLE IF NOT EXISTS `ex5`.`categoria` (
  `id` INT(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex5`.`produto categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex5`.`produto categoria` ;

CREATE TABLE IF NOT EXISTS `ex5`.`produto categoria` (
  `produto_id` INT(10) NOT NULL,
  `categoria_id` INT(10) NOT NULL,
  INDEX `fk_produto categoria_produto_idx` (`produto_id` ASC),
  INDEX `fk_produto categoria_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_produto categoria_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ex5`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ex5`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
